name: E2E / Sanity / Cron / Update Cache

on:
  schedule:
      - cron: '0 6 */7 * *'
      

jobs:
  Portfolio_E2E_Cron_Main:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Get node version
      id: node
      run: |
       echo "version=$(node -v)" >> $GITHUB_OUTPUT

    - name: Get node_modules cache
      uses: actions/cache@v3.0.2
      id: node_modules
      with:
        path: |
          **/node_modules
        key: basekey-test
      