name: E2E / Sanity / Cron

on:
  schedule:
      - cron: '0 6 * * *'
      

jobs:
  Portfolio_E2E_Cron_Main:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Get node version
      id: node
      run: |
        echo "version=$(node -v)" >> $GITHUB_OUTPUT

    - name: Get node_modules cache
      uses: actions/cache@v3.0.2
      id: node_modules
      with:
        path: |
          **/node_modules
        key: basekey-test


    - name: Run core tests
      run: npx playwright test --grep "@core" --project="Chrome_With_Media"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 5
      