name: Playwright / Sanity / Cron

on:
  schedule:
      - cron: '0 */6 * * *'
      

jobs:
  Portfolio_E2E_Cron:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npm ci
    # - name: Install Testmo CLI
    #   run: npm install --no-save @testmo/testmo-cli
    - name: Install Playwright
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npx playwright install --with-deps chromium
    - name: Run Playwright - All tests
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: npx playwright test

    # - name: Send Slack notification
    #   if: failure()
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     MSG_MINIMAL: true
    #     SLACK_USERNAME: 'e2eBot'
    #     SLACK_CHANNEL: '#portfolio-e2e-runs'
    #     SLACK_COLOR: danger
    #     SLACK_ICON: 'https://i.imgur.com/RCPwzpF.png'
    #     SLACK_TITLE: 'Scheduled E2E tests for portfolio DEV failed :poop-sad:'
    #     SLACK_MESSAGE: 'Preparing report...'
    #     SLACK_FOOTER: ''
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    # - name: Send Slack notification
    #   if: success()
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     MSG_MINIMAL: true
    #     SLACK_USERNAME: 'e2eBot'
    #     SLACK_CHANNEL: '#portfolio-e2e-runs'
    #     SLACK_COLOR: good
    #     SLACK_ICON: 'https://i1.sndcdn.com/avatars-000332935263-g0067m-t500x500.jpg'
    #     SLACK_TITLE: 'Scheduled E2E tests for portfolio DEV - Completed! :poop:'
    #     SLACK_MESSAGE: 'Preparing report...'
    #     SLACK_FOOTER: ''
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 5

    # - name: Push Testmo Report
    #   if: always()
    #   run: |
    #       npx testmo automation:run:submit \
    #         --instance "$TESTMO_URL" \
    #         --project-id 1 \
    #         --name "Core Plan Stable - Cron DEV" \
    #         --source "DEV-Github" \
    #         --results configs/testmoresults/test-results.xml \
    #   env:
    #     TESTMO_URL: ${{ secrets.TESTMO_URL }}
    #     TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}

    # - name: Get Allure history
    #   uses: actions/checkout@v3
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     ref: allure-history-staging
    #     path: allure-history-staging
    
    # - name: Test marketplace action
    #   uses: simple-elf/allure-report-action@master
    #   if: always()
    #   id: allure-report
    #   with:
    #     allure_results: allure-results
    #     gh_pages: gh-pages
    #     allure_report: allure-report
    #     allure_history: allure-history
    #     keep_reports: 20

    # - name: Deploy Allure report files to allure-history-staging branch
    #   uses: s0/git-publish-subdir-action@develop
    #   if: always()
    #   env:
    #     REPO: self   
    #     BRANCH: allure-history-staging
    #     FOLDER: ./allure-report
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     MESSAGE: "Build: ({sha}) {msg}"

    # - name: Deploy Allure report to vercel
    #   uses: s0/git-publish-subdir-action@develop
    #   if: always()
    #   env:
    #     REPO: git@github.com:[TEST]/[NAME].git
    #     BRANCH: main
    #     FOLDER: ./allure-report
    #     SSH_PRIVATE_KEY: ${{ secrets.ID_RSA_PRIV_STAGING }}
    #     MESSAGE: "Build: ({sha}) {msg}"

    # - name: Send Slack notification
    #   if: always()
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     MSG_MINIMAL: true
    #     SLACK_USERNAME: 'Github Actions'
    #     SLACK_CHANNEL: '#portfolio-e2e-runs'
    #     SLACK_COLOR: '#7c45ba'
    #     SLACK_ICON: 'https://pbs.twimg.com/profile_images/1304754508866752514/yxec5TJF_400x400.jpg'
    #     SLACK_TITLE: 'Testmo Report'
    #     SLACK_MESSAGE: 'https://[testmoname].testmo.net/automation/runs/1'
    #     SLACK_FOOTER: ''
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}